### ISSUE TITLE
Can't Progress with Lobby over 4

### ISSUE THREAD

**Issue by birukbanko** [ALittlePatate/DevourClient#26]
When making a lobby of more than 4 people we cannot kill any pigs so we can't progress in the game, specifically in Slaughterhouse, I haven't tried it for any of the older maps yet tho so maybe its just with the new map.

**Comment by Jadis0x** [comment]
After activating Azazel, players need to wait for a while before killing any pigs. This should allow the game to progress normally.

**Comment by ALittlePatate** [comment]
actually the very same thing happened to me yesterday, we were 7-8 players. This is related to the game not being made for that many players, sadly there is nothing we can do about it without re-coding the AI system entirely which is not plannet (yet)

**Comment by birukbanko** [comment]
So waiting will not allow the game to work? 

> After activating Azazel, players need to wait for a while before killing any pigs. This should allow the game to progress normally.

Were you able to beat the game with more than 4 players?

**Comment by ALittlePatate** [comment]
> So waiting will not allow the game to work?

I didn't try it

> Were you able to beat the game with more than 4 players?

I wasn't, maybe @jadis0x ?

**Comment by Jadis0x** [comment]
@ALittlePatate I tried the slaughterhouse map once in the beta version and didn't encounter any issues, but I experienced a black screen issue in the other maps..

**Comment by thoricelli** [comment]
I'm having the same issue in my server, after more than 4 players the AI breaks. There is no way to fix this right now or?

**Comment by ALittlePatate** [comment]
> I'm having the same issue in my server, after more than 4 players the AI breaks. There is no way to fix this right now or?

nope, that's a game issue soo yeah

**Comment by HackerMans69** [comment]
What's the point of adding an option to hold a server of 30 players, if you can't even play or beat the game?
