### ISSUE TITLE
Hack not working anymore

### ISSUE THREAD

**Issue by illubaby** [ALittlePatate/DevourClient#31]
After some update version of DEVOUR, it seems that your mod is not working anymore. Could u check it for me again ?

**Comment by ALittlePatate** [comment]
Hey, i just tried the thing, it works well on my side, please provide the log file from melon loader or the steps to reproduce the bug

**Comment by illubaby** [comment]
I just

> Hey, i just tried the thing, it works well on my side, please provide the log file from melon loader or the steps to reproduce the bug

Oh, i just do everything again and it work fine now. Thanks Buddy !
