### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by qeinz** [ALittlePatate/DevourClient#52]
could you publish the update into a new release please, tried the "last week" published release and get the same error you just closed few minutes ago :D

**Comment by qeinz** [comment]
@[jadis0x](https://github.com/jadis0x) jadis0x
[ 4.0](https://github.com/ALittlePatate/DevourClient/tree/4.0)
https://github.com/ALittlePatate/DevourClient/commit/1cdfd2ff02ac8d5c72ed8f59850a7a1061dd98b9
DevourClient 2.0 Update Release
Important Update for Users:
Please note that our latest release, DevourClient.dll, is not compatible with Melon Loader. This DLL is designed to be used specifically with the DLL injection method. To implement this DLL, you will need to use a suitable DLL injector tool of your choice.

Does this count for the new relaese aswell?

**Comment by ALittlePatate** [comment]
we'll make a new release when new features will be coded, for now you have to compile it yourself
