### ISSUE TITLE
esp color not changing

### ISSUE THREAD

**Issue by qeinz** [ALittlePatate/DevourClient#54]
![image](https://github.com/ALittlePatate/DevourClient/assets/66924611/2f0059a0-268c-4bd6-9db5-63f2760f178e)

**Comment by ALittlePatate** [comment]
thanks for the report, i fixed it in [f9ce069efd3e2d1d10400654c4c35873d610926a](https://github.com/ALittlePatate/DevourClient/commit/f9ce069efd3e2d1d10400654c4c35873d610926a)
