### ISSUE TITLE
 failed to load a specific file because it is not a valid .NET assembly

### ISSUE THREAD

**Issue by Blabpav** [ALittlePatate/DevourClient#63]
![image](https://github.com/user-attachments/assets/299f9de6-b210-4815-846d-160f76bbb36b)

**Comment by KnucklesB** [comment]
[DevourClient](https://github.com/ALittlePatate/DevourClient) is not a melon loader modification; you can use this injector [LuminousInjector](https://github.com/jadis0x/LuminousInjector/releases/tag/v1.1) made by [jadis0x Jadis0x](https://github.com/jadis0x), one of the project contributors.

Open it and select the DLL, it should inject into your game
