### ISSUE TITLE
Use cheat game ontology to crash

### ISSUE THREAD

**Issue by xBaoSummer** [ALittlePatate/DevourClient#66]
Hello, developers, I used the cheat game in the slaughterhouse map to crash error, I provided the log and error picture below.
Trigger conditions:
1. In multiplayer play, an error will be reported during entering the Slaughterhouse game animation (already triggered twice)
2. When a single player enters the game, the first imps are illuminated incorrectly
3. In single-player games I get errors when I close the game directly in the taskbar
[DevourClient.txt](https://github.com/user-attachments/files/16334945/DevourClient.txt)
![微信截图_20240722220142](https://github.com/user-attachments/assets/4639219e-2ded-47d0-a5c9-98d48eaf012c)

**Comment by Xo1ezw** [comment]
I started the test function one by one, which may be caused by the unlimited ultraviolet function. After I turned off the ultraviolet function, it ran stably, and there was no game crash in the game for the time being

**Comment by ALittlePatate** [comment]
I believe it got fixed
