### ISSUE TITLE
Exp Modifier

### ISSUE THREAD

**Issue by lI999Il** [ALittlePatate/DevourClient#7]
Not sure if I need to enable this during the game or after, I had checked the box before the game started and changed it to 50000. It gave me the exp but when I clicked close it didn't give me my rank. I compiled it as instructed and had no issues, please let me know if there's anything I can do to fix it. -Jake

**Comment by ALittlePatate** [comment]
hi ! This is still a very new feature, i had the same problem with huge amounts of exp, during the test i was trying with 5k exp and it worked well + keeping my rank. Maybe the game doesn't allow you to get a shit ton of exp (?)

**Comment by KorruptedKlout** [comment]
I was thinking the same thing, just want to share to make sure I wasn't getting anything wrong! I love the project and big thanks/props to you for making it! 💯 I'll try it out and see how it works.

**Comment by KorruptedKlout** [comment]
> hi ! This is still a very new feature, i had the same problem with huge amounts of exp, during the test i was trying with 5k exp and it worked well + keeping my rank. Maybe the game doesn't allow you to get a shit ton of exp (?)

Fixed it! Can't go higher than the exp needed to level up apparently, hopefully we can find a way to make the set ranks permanent! Cheers!
