### ISSUE TITLE
Quelques questions pour les novices

### ISSUE THREAD

**Issue by keterforcpp** [ALittlePatate/DevourClient#77]
Merci pour votre projet, c’est très bon.J’ai une question, puis-je utiliser directement les fichiers.dll fournis dans la section "release"? Est-ce que cela fonctionnera si je place ce fichier.dll directement dans le répertoire du jeu?

**Comment by ALittlePatate** [comment]
Le (dernier) Dll dans Release fonctionnera avec MelonLoader
pour la deuxième question je t'invite à lire le readme.

**Comment by keterforcpp** [comment]
> Le (dernier) Dll dans Release fonctionnera avec MelonLoader pour la deuxième question je t'invite à lire le readme.

Merci pour votre aide. Le programme fonctionne normalement, bien qu’il ait fallu un certain temps pour résoudre cela.

**Comment by keterforcpp** [comment]
J’ai trouvé une fonction quand j’ai regardé dans le code, « void MessageSpam(string message) », le commentaire de la fonction a écrit « //TOFIX : not spamming longer :/ », j’ai utilisé un logiciel de traduction pour vérifier le commentaire, je ne sais pas si je peux comprendre correctement ce commentaire, cela signifie-t-il que cette fonction ne fonctionne pas correctement ?
